### ISSUE TITLE
Missing libgcc_s_dw2-1.dll when using some tools

### ISSUE THREAD

**Issue by Akis-02** [supadupaplex/ps2-hl-tools#1]
When using some tools a message pops up telling me that libgcc_s_dw2-1.dll is missing

**Comment by supadupaplex** [comment]
Hi. Can you test if this build works for you?

[test.zip](https://github.com/supadupaplex/ps2-hl-tools/files/6182629/test.zip)

**Comment by Akis-02** [comment]
> Hi. Can you test if this build works for you?
> 
> [test.zip](https://github.com/supadupaplex/ps2-hl-tools/files/6182629/test.zip)

Yep, when porting models it works

**Comment by Akis-02** [comment]
Also this might be weird but is there a way that i can speak to you? like steam or discord if you can?

**Comment by supadupaplex** [comment]
Patch hash: ec68ffa37f985d872e39e2c78e34f0d63a97b3c6

Akis-02, you can send email to alexeyln94@gmail.com
